apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: test-appdeux
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: test-appdeux
 template: 
   metadata: 
    labels: 
     app: test-appdeux
     env: prod 
   spec: 
    containers: 
    - name: test-container 
      image: nginx:alpine
      ports:
           â€”containerPort: 80
